version: '3'
services:
  myapp:
    image: tiangolo/meinheld-gunicorn-flask
    container_name: footyapp-portainer
    networks:
      br0:
        ipv4_address: 192.168.0.233
    ports:
      - "80:80"
    environment:
      - WEB_CONCURRENCY=1
      - PYTHONUNBUFFERED=1
    volumes:
      - /mnt/user/share/docker/footyapp/tokens/:/tokens
    command: ["echo", "Container is up and running!"]
networks:
  br0:
    external: true
    name: br0
